export { default as Avatar } from './Avatar'
export { default as ErrorBoundary } from './ErrorBoundary'
export { default as AttachmentSlider } from './AttachmentSlider'

// Phase 1 primitives
export { default as Modal } from './Modal'
export type { ModalProps } from './Modal'
export { default as Button } from './Button'
export type { ButtonProps, ButtonVariant, ButtonSize } from './Button'
export { default as IconButton } from './IconButton'
export type { IconButtonProps } from './IconButton'
export { default as FormField } from './FormField'
export { Input, Textarea, Select, fieldStyle } from './Input'
export { default as Popover } from './Popover'
export type { PopoverProps, PopoverPlacement } from './Popover'
export { default as Spinner } from './Spinner'
export { default as EmptyState } from './EmptyState'
export { default as Badge } from './Badge'
export type { BadgeTone } from './Badge'
